function NotebookListCtrl($scope) {
  $scope.notebooks = [
    {"name": "Lenovo",
     "procesor": "Intel i5",
     "age": 2014},
    {"name": "Toshiba",
     "procesor": "Intel i7",
     "age": 2013},
    {"name": "Toshiba",
     "procesor": "Intel core 2 duo",
     "age": 2012},
    {"name": "HP",
     "procesor": "Intel core 2 duo",
     "age": 2011},
    {"name": "Acer",
     "procesor": "AMD",
     "age": 2013},
    {"name": "Lenovo",
     "procesor": "Intel i5",
     "age": 2015},
    {"name": "Toshiba",
     "procesor": "Intel i7",
     "age": 2014},
    {"name": "Lenovo",
     "procesor": "Intel i5",
     "age": 2012},
    {"name": "Toshiba",
     "procesor": "Intel i7",
     "age": 2013},
    {"name": "Toshiba",
     "procesor": "Intel core 2 duo",
     "age": 2012},
    {"name": "HP",
     "procesor": "Intel core 2 duo",
     "age": 2012},
    {"name": "Acer",
     "procesor": "AMD",
     "age": 2015},
    {"name": "Lenovo",
     "procesor": "Intel i5",
     "age": 20111},
    {"name": "Toshiba",
     "procesor": "Intel i7",
     "age": 2008},
    {"name": "Lenovo",
     "procesor": "Intel i5",
     "age": 2011},
    {"name": "Toshiba",
     "procesor": "Intel i7",
     "age": 2010},
    {"name": "Toshiba",
     "procesor": "Intel core 2 duo",
     "age": 2008},
    {"name": "HP",
     "procesor": "Intel core 2 duo",
     "age": 2012},
    {"name": "Acer",
     "procesor": "AMD",
     "age": 2014},
    {"name": "Lenovo",
     "procesor": "Intel i5",
     "age": 2009},
    {"name": "Toshiba",
     "procesor": "Intel i7",
     "age": 2013}
  ];
  $scope.orderList = "name";
}
